#####################################################################
#																	#
#			<Project>/Makefile :: Compile the full scanner			#
#																  	#
#####################################################################
# Usage :
# 	| make   		// compile all binaries
#	| make clean	// clean all binaries

CC: g++ -Wall -g

BINS:

all: $(BINS)

###########################################################
# 				Compile binaries from .o				  #
###########################################################